image: alpine:latest

pages:
  stage: deploy
  script:
  - apk update
  - apk add unzip
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
